---
apiVersion: stackit-operator.webhippie.de/v1alpha1
kind: ServiceAccountCredentials

metadata:
  name: serviceaccountcredentials-sample
  namespace: default
  labels:
    app.kubernetes.io/name: stackit-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  projectId: 00000000-0000-0000-0000-000000000000
  region: eu01

  serviceAccountKey:
    secretKeyRef:
      name: stackit-service-account
      key: key.json

...
